export const projectTypes = [
    { value: "software", label: "Software Development" },
    { value: "marketing", label: "Marketing Campaign" },
    { value: "design", label: "Design & Creative" },
    { value: "construction", label: "Construction" },
    { value: "education", label: "Education/Training" },
    { value: "finance", label: "Finance & Accounting" },
    { value: "human_resources", label: "Human Resources" },
    { value: "research", label: "Research & Development" },
    { value: "event", label: "Event Planning" },
    { value: "healthcare", label: "Healthcare" },
    { value: "non_profit", label: "Non-Profit" },
    { value: "personal", label: "Personal" },
    { value: "other", label: "Other" },
]; 

export const jobFields = [
    { id: 1, name: "Software Engineer" },
    { id: 2, name: "Data Scientist" },
    { id: 3, name: "Product Manager" },
    { id: 4, name: "Web Developer" },
    { id: 5, name: "Graphic Designer" },
    { id: 6, name: "Marketing Specialist" },
    { id: 7, name: "Sales Associate" },
    { id: 8, name: "Human Resources Manager" },
    { id: 9, name: "Project Coordinator" },
    { id: 10, name: "System Analyst" },
    { id: 11, name: "Database Administrator" },
    { id: 12, name: "UX/UI Designer" },
    { id: 13, name: "Network Engineer" },
    { id: 14, name: "Quality Assurance Tester" },
    { id: 15, name: "Business Analyst" },
  ];